/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef, useState } from "react";
import { useGLTF } from "@react-three/drei";

export function CarModel(props) {
  const { nodes, materials } = useGLTF(
    "/models/uploads_files_3132934_FREE_CAR_01.gltf"
  );

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.car_body.geometry}
        material={materials["BASIC COLOR"]}
        position={[0, 0, 0.08]}
        rotation={[0, -1.571, 0]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.door_l.geometry}
          material={materials["BASIC COLOR"]}
          position={[0.914, 0.683, 0.638]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.win_door_l001.geometry}
            material={materials.WINDOW}
            position={[-0.155, 0.696, -0.735]}
          />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.door_r.geometry}
          material={materials["BASIC COLOR"]}
          position={[-0.914, 0.683, 0.638]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.win_door_r001.geometry}
            material={materials.WINDOW}
            position={[0.155, 0.696, -0.735]}
          />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.interior.geometry}
          material={materials["BASIC COLOR"]}
          position={[0.941, 0.6, -0.074]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[0.445, 0.398, 0.398]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.number.geometry}
          material={materials["BASIC COLOR"]}
          position={[0, 0.793, -1.768]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.wheel_bl.geometry}
          material={materials["BASIC COLOR"]}
          position={[0.782, 0.325, -1.241]}
          rotation={[0, 1.571, 0]}
          scale={0.325}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.wheel_br.geometry}
          material={materials["BASIC COLOR"]}
          position={[-0.782, 0.325, -1.241]}
          rotation={[0, 1.571, 0]}
          scale={0.325}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.wheel_fl.geometry}
          material={materials["BASIC COLOR"]}
          position={[0.782, 0.325, 1.071]}
          rotation={[0, 1.571, 0]}
          scale={0.325}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.wheel_fr.geometry}
          material={materials["BASIC COLOR"]}
          position={[-0.782, 0.325, 1.071]}
          rotation={[0, 1.571, 0]}
          scale={0.325}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.windows.geometry}
          material={materials.WINDOW}
        />
      </mesh>
    </group>
  );
}

useGLTF.preload("/models/uploads_files_3132934_FREE_CAR_01.gltf");
