/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export function CityFarBG(props) {
  const { nodes, materials } = useGLTF("/models/City_farBG.gltf");

  const meshRef = useRef();

  // Animation function
  useFrame((state, delta) => {
    // Update the x position of the mesh to create animation
    meshRef.current.position.x += 0.0 * delta;

    // Reset x position if it goes beyond a certain point
    if (meshRef.current.position.x > 40) {
      meshRef.current.position.x = -40; // Reset to the starting point
    }
  });
  return (
    <group {...props} dispose={null} ref={meshRef}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane002.geometry}
        material={materials["Material.035"]}
        position={[0.482, -0.313, 1.564]}
      />
    </group>
  );
}

useGLTF.preload("/models/City_farBG.gltf");
