/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export function CityFarBG(props) {
  const { nodes, materials } = useGLTF("/models/City_farBG.gltf");

  const meshRef = useRef();

  // Animation function
  useFrame((state, delta) => {
    const speed = 0.05; // Adjust the speed as needed
    const amplitude = 15; // Adjust the amplitude as needed

    // Update the x position of the mesh to create animation
    meshRef.current.position.x += delta * speed;

    // Use sine wave to create a smooth back-and-forth motion
    meshRef.current.position.x =
      Math.sin(state.clock.elapsedTime * speed) * amplitude;
  });

  return (
    <group {...props} dispose={null} ref={meshRef}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane002.geometry}
        material={materials["Material.035"]}
        position={[-10, -0.313, 1.564]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane002.geometry}
        material={materials["Material.035"]}
        position={[-320, 180, -100]}
        scale={[5, 5, 5]}
      />
    </group>
  );
}

useGLTF.preload("/models/City_farBG.gltf");
